# Generated by Django 2.1.2 on 2018-11-12 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integration_config', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('secret', models.TextField()),
                ('client_id', models.CharField(max_length=100)),
                ('callbackUrl', models.TextField()),
                ('scope', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('integration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration_config.IntegrationConf')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
