# Generated by Django 2.1.2 on 2018-11-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='oauth_consumer_key',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
