# Generated by Django 2.1.2 on 2018-10-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_callbackurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='app',
            field=models.CharField(choices=[('Strava', 'Strava')], max_length=30),
        ),
    ]
