# Generated by Django 2.1.2 on 2018-11-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_oauth_consumer_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='oauth_consumer_key',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
