# Generated by Django 2.1.2 on 2018-10-26 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integration_config', '0001_initial'),
        ('project', '0004_auto_20181024_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='app',
        ),
        migrations.AddField(
            model_name='project',
            name='integration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration_config.IntegrationConf'),
        ),
    ]
