# Generated by Django 2.1.2 on 2018-10-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationconf',
            name='form_class_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='integrationconf',
            name='oauth_class_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
